# Generated by Django 5.0.6 on 2024-05-12 10:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="last update date",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Custom setted system name",
                    ),
                ),
                ("cpu_name", models.CharField(max_length=200)),
                ("gpu_name", models.CharField(blank=True, max_length=200, null=True)),
                ("ram", models.IntegerField()),
                ("ram_available", models.IntegerField()),
                ("swap", models.IntegerField()),
                ("swap_available", models.IntegerField()),
                ("load_avg_last_min", models.FloatField()),
                ("load_avg_last_5_min", models.FloatField()),
                ("load_avg_last_15_min", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NetworkStatsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="last update date",
                    ),
                ),
                (
                    "receive_megabytes",
                    models.FloatField(verbose_name="Network recieved megabytes"),
                ),
                (
                    "transmit_megabytes",
                    models.FloatField(verbose_name="Network transmitted megabytes"),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_statistics",
                        to="system.systemmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MemoryStatsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="last update date",
                    ),
                ),
                (
                    "usage_megabytes",
                    models.FloatField(verbose_name="System memory usage megabytes"),
                ),
                (
                    "usage_percentage",
                    models.FloatField(verbose_name="System memory usage percentage"),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_statistics",
                        to="system.systemmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DiskStatsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="last update date",
                    ),
                ),
                (
                    "usage_percentage",
                    models.FloatField(verbose_name="Disk usage percentage"),
                ),
                (
                    "usage_megabytes",
                    models.FloatField(verbose_name="Disk usage megabytes"),
                ),
                ("available", models.FloatField(verbose_name="Available disk space")),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disk_statistics",
                        to="system.systemmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CPUStatsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="last update date",
                    ),
                ),
                (
                    "utilization",
                    models.FloatField(verbose_name="CPU utilization percentage"),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpu_statistics",
                        to="system.systemmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
