services:
  auto_ml_flow:
    image: mawlle/auto_ml_flow:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: >
      sh -c "python ./manage.py migrate &&
      gunicorn auto_ml_flow.wsgi:application --workers 8 --threads 8 --limit-request-line 10000 -t=600 --bind 0.0.0.0:${APP_PORT}"

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 90 express_starter

  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT}

volumes:
  postgres_storage: {}
