services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth=md5
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT}
  
  pgbouncer:
    image: edoburu/pgbouncer:latest
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_USERS=${POSTGRES_USER}
      - MAX_CLIENT_CONN=1000
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  postgres_storage: {}
